- .babelrc
- .gitignore
- .travis.yml
- README.md
- babel.config.js
- package-lock.json
- package.json
* Configure Travis CI
* Install Jest
* Install Babel
* Add Travis build badge to README.md
> Repository and Project Setup

- src/App.css
- src/App.js
- src/components/GasStationData.js
- src/components/styles/GasStationData.css
* Create FIND button
* Create gas station list from an array of objects
* Currently only has placeholder data, so it will need to be updated to use the actual object's field names once we have the data
Check out what it looks like [here](https://rtgc-test.herokuapp.com/). The spacing is weird, but it's just the CSS and that can be changed later once we have all the UI elements.
> Write GasStationData Module UI

- package-lock.json
- package.json
- src/components/GasStationData.js
Get location is working!!! Please review and merge with da masta!
> Ross McGuyer/get location

- .travis.yml
> Update Node.js Version on Travis CI

- package-lock.json
- package.json
- src/App.js
- src/components/CarInfo.js
- src/components/GasStationData.js
Hey. This needs some review. Make sure everything is working and nothing breaks.
> Ross mcguyer mpg text

- src/components/GasStationData.js
- src/components/styles/GasStationData.css
* Update debug/dummy data
* Add FIND show gas station list functionality.
* Add fixed point notation to gas prices
* Add overflow scroll CSS
> Gas Station Data Updates

- src/components/GasStationData.js
- src/components/StationCalculation.js
* Create station calculation module with:
* comparator functions
* distance calculation
* Add top 5 functionality
> Add Top Five Gas Station Functionality

- src/components/GasStationData.js
- src/components/styles/GasStationData.css
**Updated gas station display to include distance to station.
> **Altered style sheet to account for shitty scroll bars

- src/components/styles/CarInfo.css
Edit CSS to change depending on screen width.
> Fix Mobile Dropdown Layout

- src/components/CarInfo.js
- src/components/styles/CarInfo.css
**Added CarInfoContainer to CarInfo.js
**Updated CarInfo.css to make website look sightly better.
> Altered CarInfo.js

- src/components/FilterPopup.js
Currently the input field takes input, but only the previously entered data.
We will have to use a submit button to take the current value.
> Add Max Distance Input Field

- package-lock.json
- package.json
- src/App.js
- src/components/Map.js
**Added google map to website.
**Currently flies off the page.
**need help with the css code to stylize it.
**Remember to use NPM install because there are some new dependencies.
> Added Map to Website app

- package-lock.json
- package.json
- src/data/CarData.js
- src/data/FuelEconomyGov.js
- tests/FuelEconomy.test.js
* Create template CarData class
* Create FuelEconomyGov class
* Write tests for FuelEconomyGov
> Get Fuel Economy Data

- src/components/GasStationData.js
- src/components/Map.js
- src/components/StationCalculation.js
- src/components/styles/Map.css
**Popup windows now display gas station information.
> Ross mcguyer/add marker popup windows

- src/components/StationCalculation.js
- tests/StationCalculation.test.js
* Add functions for Chass calculation and comparison to StationCalculation module
* Write tests for Chass calculations
> Add Chass Calculation and Comparison

- src/components/GasStationData.js
- src/components/StationCalculation.js
- tests/StationCalculation.test.js
Change GasStationData to output smartly calculated gas station data.
> Change Station List to Output Smart Calculation

- src/data/StationCalculation.js
- tests/StationCalculation.test.js
Wrote tests for `calc`-/`compareDistance`, `comparePrice`, and `degToRad`.
Also rewrote comparison functions using `Math.sign` to decrease code and make it less prone to errors.
> Write Tests for StationCalculation Module

- package-lock.json
- package.json
- src/components/CarOptions.js
- src/components/styles/CarOptions.css
* When user chooses their car year, make, model, and option, their city and highway MPG are displayed
* User can drag the slider for current tank of gas(However, it's not used yet and doesn't display number after user slides it. It does show number when the user is dragging it )
> Displayed Car MPG and Created Slider

- README.md
- src/components/CarOptions.js
- src/components/GasStationData.js
- src/components/styles/CarOptions.css
* Display user's car information on the Car Info page
* Change cookie `mpg` to `combMPG`
* Save highway and city mpg to cookies
* Update `README.md`
> Display Car Info

- src/components/CarOptions.js
- src/components/GasStationData.js
- src/components/styles/GasStationData.css
* Change tank fill slider to default to the value stored in cookies
* Cookies for `tankFill` now starts with a default value of .5
* Change layout of gas stations list
* Change map width
* Change Find page layout for mobile
> Make Changes to Find and Car Options Formatting

- src/App.js
- src/components/CarOptions.js
- src/components/GasStationData.js
- src/components/Map.js
- src/components/styles/Map.css
* Master wouldn't load since form wasn't declared in CarOption.js
* Commented console logs in map.js and app.js
* Deleted blue border background in map.css
> Form Error Fix

- src/components/CarOptions.js
Selecting the default empty element from a dropdown menu caused the page to crash.
> Fix Empty Element Select Crash

- src/components/GasStationData.js
Previously, we filtered the already sorted and sliced data, so it would
display <= 5 stations. Now we always display 5 stations regardless of
what filters are selected.
> Fix Number of Stations Displayed After Filtering

- src/components/Map.js
- src/components/styles/Map.css
**Added a blue marker to indicate the user's location when they opene…
**No changies. Called it.
> New marker added to map to show user location.

- src/components/GasStationData.js
- src/components/styles/GasStationData.css
* Create FuelPrice component
* Add unleaded plus and premium fuel prices in a collapsible Reactstrap component
* Change cursor to pointer when mousing over the fuel prices
* Clean up `GasStationData.js`
* Remove console logs
* Remove TODO and old commented code
* Remove unnecessary break statements
> Add Collapsible Fuel Prices

- package.json
- src/components/GasStationData.js
- src/components/GasStationFilterContainer.js
- src/components/Map.js
- src/data/GasStationWrapper.js
- src/data/StationCalculation.js
- tests/StationCalculation.test.js
* Finished implementing filter by gas grade. If a gas grade is checked, then a gas station without that gas grade will not appear on the list.
* Fixed issue that prevented the max distance textbox from being empty
* When max distance textbox is empty or 0, the max distance filter is not used.
> Ed carrasco/gas grades

- src/components/GasStationData.js
- src/components/GasStationFilterContainer.js
* added Get Directions button to each gas station on list
* Opens a new window to Google Maps with the latitude and longitude
> added Get Directions button to each gas station on list
